name: 'Self Cronjob'

defaults:
  run:
    shell: bash
    working-directory: ./

on:
  push:
  schedule:
    - cron: '25 6 * * *'

jobs:
  days:
    runs-on: ubuntu-latest
    env:
      BEIAN_URI: http://aliyun.haujilo.xyz/
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: 'Keep Beian alive'
        run: bash ./days.sh
