name: 'Daily work'

defaults:
  run:
    shell: bash
    working-directory: ./

on:
  schedule:
    - cron: '25 6 * * *'

jobs:
  Keep-Beian-Alive:
    runs-on: ubuntu-latest
    env:
      BEIAN_URI: http://aliyun.haujilo.xyz/
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: 'Keep beian alive'
        run: cd jobs && ./keep_beian_alive.sh
